# Use a Go image as the base
FROM golang:1.24.0-alpine

# Install git, bash, and the C compiler toolchain
RUN apk add --no-cache git bash build-base

# Install air from its new official location
RUN go install github.com/air-verse/air@latest

# Set the working directory
WORKDIR /app

# Copy the go.mod and go.sum files to cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application source code
COPY . .

# Expose the port the application will run on
EXPOSE 4001

# The command to start the application with air
CMD ["air"]